package com.nwnu.averweb.model;


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_roleprivilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysRoleprivilege {
    /**
     * 主键
     * Id
     */
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * 角色编码
     * rolecode
     */
    private String rolecode;

    /**
     * 权限编码集
     * privilegecode
     */
    private String privilegecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleprivilege.Id
     *
     * @return the value of sys_roleprivilege.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleprivilege.Id
     *
     * @param id the value for sys_roleprivilege.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleprivilege.rolecode
     *
     * @return the value of sys_roleprivilege.rolecode
     *
     * @mbggenerated
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleprivilege.rolecode
     *
     * @param rolecode the value for sys_roleprivilege.rolecode
     *
     * @mbggenerated
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleprivilege.privilegecode
     *
     * @return the value of sys_roleprivilege.privilegecode
     *
     * @mbggenerated
     */
    public String getPrivilegecode() {
        return privilegecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleprivilege.privilegecode
     *
     * @param privilegecode the value for sys_roleprivilege.privilegecode
     *
     * @mbggenerated
     */
    public void setPrivilegecode(String privilegecode) {
        this.privilegecode = privilegecode == null ? null : privilegecode.trim();
    }
}