package com.nwnu.averweb.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysUser {
    /**
     * 主键
     * id
     */
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * 电子邮件
     * email
     */
    private String email;

    /**
     * 密码
     * pwd
     */
    private String pwd;

    /**
     * 角色编码
     * rolecode
     */
    private String rolecode;

    /**
     * 姓名
     * name
     */
    private String name;

    /**
     * 性别
     * gender
     */
    private String gender;

    /**
     * 民族
     * nation
     */
    private String nation;

    /**
     * 籍贯
     * jiguan
     */
    private String jiguan;

    /**
     * 出生年月
     * birthday
     */
    private String birthday;

    /**
     * 最终学位
     * graduate
     */
    private String graduate;

    /**
     * 研究方向
     * research
     */
    private String research;

    /**
     * 职称
     * professional
     */
    private String professional;

    /**
     * 单位名称
     * unit
     */
    private String unit;

    /**
     * 联系地址
     * address
     */
    private String address;

    /**
     * 邮政编码
     * post_code
     */
    private String postCode;

    /**
     * 手机号码
     * phone
     */
    private String phone;

    /**
     * 密码提示问题
     * question
     */
    private String question;

    /**
     * 密码提示答案
     * answer
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.pwd
     *
     * @return the value of sys_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.pwd
     *
     * @param pwd the value for sys_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.rolecode
     *
     * @return the value of sys_user.rolecode
     *
     * @mbggenerated
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.rolecode
     *
     * @param rolecode the value for sys_user.rolecode
     *
     * @mbggenerated
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.gender
     *
     * @return the value of sys_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.gender
     *
     * @param gender the value for sys_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nation
     *
     * @return the value of sys_user.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nation
     *
     * @param nation the value for sys_user.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.jiguan
     *
     * @return the value of sys_user.jiguan
     *
     * @mbggenerated
     */
    public String getJiguan() {
        return jiguan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.jiguan
     *
     * @param jiguan the value for sys_user.jiguan
     *
     * @mbggenerated
     */
    public void setJiguan(String jiguan) {
        this.jiguan = jiguan == null ? null : jiguan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birthday
     *
     * @return the value of sys_user.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birthday
     *
     * @param birthday the value for sys_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.graduate
     *
     * @return the value of sys_user.graduate
     *
     * @mbggenerated
     */
    public String getGraduate() {
        return graduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.graduate
     *
     * @param graduate the value for sys_user.graduate
     *
     * @mbggenerated
     */
    public void setGraduate(String graduate) {
        this.graduate = graduate == null ? null : graduate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.research
     *
     * @return the value of sys_user.research
     *
     * @mbggenerated
     */
    public String getResearch() {
        return research;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.research
     *
     * @param research the value for sys_user.research
     *
     * @mbggenerated
     */
    public void setResearch(String research) {
        this.research = research == null ? null : research.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.professional
     *
     * @return the value of sys_user.professional
     *
     * @mbggenerated
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.professional
     *
     * @param professional the value for sys_user.professional
     *
     * @mbggenerated
     */
    public void setProfessional(String professional) {
        this.professional = professional == null ? null : professional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.unit
     *
     * @return the value of sys_user.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.unit
     *
     * @param unit the value for sys_user.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.address
     *
     * @return the value of sys_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.address
     *
     * @param address the value for sys_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.post_code
     *
     * @return the value of sys_user.post_code
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.post_code
     *
     * @param postCode the value for sys_user.post_code
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.question
     *
     * @return the value of sys_user.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.question
     *
     * @param question the value for sys_user.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.answer
     *
     * @return the value of sys_user.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.answer
     *
     * @param answer the value for sys_user.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}